apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blazeface-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.blazeface.domain }}
    http:
      paths:
      - pathType: Prefix
        path: /api/face 
        backend:
          service:
            name: blazeface-service
            port:
              number: 8081
