apiVersion: v1
kind: Service
metadata:
  name: blazeface-service
spec:
  type: ClusterIP
  selector:
    run: sealos-blazeface
  ports:
  - name: blazeface
    port: 8081
    targetPort: 8081
  - name: http-server
    port: 8080
    targetPort: 8080
